services:
  mafl:
    image: r0gger/mafl
    container_name: mafl
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./mafl/config.yml:/app/data/config.yml
      #- ./mafl/favicons://app/public/favicons
